### ISSUE TITLE
Does this work in multiplayer?

### ISSUE THREAD

**Issue by tonytonyistony** [PenguinDOOM/stronghold_save_credits#2]
Tried loading this into my Stronghold server, but it doesnt seem to save credits after logout.

**Comment by PenguinDOOM** [comment]
Yes, it works. But you need to use the database.

**Comment by tonytonyistony** [comment]
Damn thats some excellent response time! Kudos TY!

I assume the database is what is hosted in this github?
Does each player need to have these files or just the server or both?

**Comment by PenguinDOOM** [comment]
Both the server and the client must have it, but the client can get it automatically using doomseeker.

**Comment by tonytonyistony** [comment]
10-4 Trying it out now. Thanks for the help.

**This is my load order for documentation purposes.**
-file strnghld_v1.pk3
strnghld_violence_v4.pk3
strongholdeditsnfixesv1.1patchv4.1.pk3
strongholditemsv7.1.pk3
strongholdrejuvenated-v6d.pk3
stronghold_save_credits_v5_1.pk3

_Updated_

**Comment by PenguinDOOM** [comment]
It is recommended that stronghold_save_credits be loaded at the end.

**Comment by tonytonyistony** [comment]
Ok that didn't work. I hate to be a pain but could you provide more detailed instructions?

So my load order is above. 
Do I have to add db file to the load order? Because it didnt download it automatically to my client.

I noticed that there are admin commands in the change log. Do you have to initiate the save commands for it to work?

**Comment by PenguinDOOM** [comment]
Set up your database with the **databasefile.** This will allow you to save the global bank. To save each player's credits you need to create an account at [http://auth.zandronum.com/](http://auth.zandronum.com/) and login to the console in game by typing **"login username password"**.

**Comment by PenguinDOOM** [comment]
Set up your database with the **databasefile.** This will allow you to save your global bank. To save player's credits by creating an account at [http://auth.zandronum.com/](http://auth.zandronum.com/) and then in game login to the console by typing **"login username password"**.

**Comment by tonytonyistony** [comment]
Ive gotten the admin menu open, the player menu open, Ive registered to the zandronum auth system. But Im still a little confused about the "databasefile". I downloaded your git and extracted it to the server and my client. I dont see any file that looks to be a database file. What am I missing pertaining to the "databasefile"?

**Comment by PenguinDOOM** [comment]
Add "databasefile any name" to the command line options when creating the server.
For example, "databasefile test.db" will create test.db and save it there.

**Comment by tonytonyistony** [comment]
ah! I get it now. I also restored my credits from the online database as well. I got it working! Thanks for being patient with me. You should put this additional info in your readme.md to help the next guy. Thanks again and thanks for the modding efforts. I have 3 dudes excited as hell to save their credits!
