### ISSUE TITLE
Getting SQL logic error constantly

### ISSUE THREAD

**Issue by mindphaseproductions** [PenguinDOOM/stronghold_save_credits#6]
Hello,

I setup this mod on my stronghold rejuvenated server and seem to be having issues with constantly having "Could not execute statement. Error: SQL logic error". Is this something you can help with?

I'm using a docker-container to load the server. The actual .db file loads fine, just seem to be having "SQL logic error" popping up constantly.

```
Could not execute statement. Error: SQL logic error
Could not execute statement. Error: SQL logic error
Could not execute statement. Error: SQL logic error
Could not execute statement. Error: SQL logic error
Could not execute statement. Error: SQL logic error
Saved Server Data
Client 0 has logged in successfully as 'mindphase'.
mindphase joined the game.
Could not execute statement. Error: SQL logic error
Create player0's account.
Could not execute statement. Error: SQL logic error
Saved player0's credits.
client mindphase (1.1.1.1:10667) disconnected.
Connect (v3.1): 1.1.1.1:10667
Error Traversing Database for ipnum = 1677667239 - Perhaps database is corrupt?
mindphase (1.1.1.1:10667) has connected. (from: N/A)
Client 0 has logged in successfully as 'mindphase'.
mindphase joined the game.
Could not execute statement. Error: SQL logic error
Create player0's account.
Could not execute statement. Error: SQL logic error
Saved player0's credits.
client mindphase (1.1.1.1:10667) disconnected.
```

**Comment by PenguinDOOM** [comment]
I think that error is a setup issue, not my mod.
Please check the server and SQL configuration. If it doesn't fix it, please ask someone on zandronum discord.

**Comment by mindphaseproductions** [comment]
Could be, however, the instructions aren't exactly straight forward on this mod for beginners like myself.

Essentially what I did respective to setting the server up with your mod was, set the Auth host, and create a database file in the config, and added your .pk3 on the server in the correct load order you mentioned on the Zandronum forums. That's essentially it. Database file loads fine, I am able to login to the account through the game console.

Would you be able to provide more detailed steps in the Readme? If not, I'll go ahead and reach out to the community.

Thanks for your time.

**Comment by mindphaseproductions** [comment]
Closing as it may not be related to mod.
